Team-Trit/donworry-ios

- Projects/DonWorry/Sources/UI/Alarm/AlarmViewController.swift
> ✨ 알림 엠티뷰 UI 

- Projects/DonWorry/Sources/Domain/Auth/Repository/UserRepository.swift
- Projects/DonWorry/Sources/Domain/Image/Repository/ImageRepository.swift
- Projects/DonWorry/Sources/UI/Alarm/AlarmViewController.swift
- Projects/DonWorry/Sources/UI/Profile/ProfileViewController.swift
- Projects/DonWorry/Sources/UI/Profile/ProfileViewReactor.swift
> ✨ 프로필 이미지 수정하기 

- Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewReactor.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/Views/FileCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListReactor.swift
- Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListViewController.swift
- Projects/DonWorry/Sources/UI/Splash/SplashViewController.swift
- Projects/DonWorry/SupportingFiles/DonWorry-Info.plist
- Projects/DonWorryNetworking/Sources/DTO/PatchUserDTO.swift
> ✨ 정산 시작 시 오류케이스 수정

- Projects/DesignSystem/Sources/TextField/LimitTextField.swift
- Projects/DonWorry/Sources/Domain/Auth/Error/AuthError.swift
- Projects/DonWorry/Sources/Domain/Auth/Model/AuthModels.swift
- Projects/DonWorry/Sources/Domain/Auth/Repository/AuthRepository.swift
- Projects/DonWorry/Sources/Domain/Auth/UseCase/CheckNicknameUseCase.swift
- Projects/DonWorry/Sources/Domain/Auth/UseCase/LogoutUseCase.swift
- Projects/DonWorry/Sources/UI/Auth/AgreeTerm/AgreeTermViewController.swift
- Projects/DonWorry/Sources/UI/Auth/AgreeTerm/AgreeTermViewReactor.swift
- Projects/DonWorry/Sources/UI/Auth/AgreeTerm/Components/AgreeTermTableViewCell.swift
- Projects/DonWorry/Sources/UI/Auth/EnterUserInfo/EnterUserInfoViewController.swift
- Projects/DonWorry/Sources/UI/Auth/EnterUserInfo/EnterUserInfoViewReactor.swift
- Projects/DonWorry/Sources/UI/Profile/ProfileViewReactor.swift
- Projects/DonWorry/Sources/UI/ProfileEditView/NicknameEditViewController.swift
- Projects/DonWorry/Sources/UI/ProfileEditView/NicknameEditViewReactor.swift
- Projects/DonWorryNetworking/Sources/APIs/User/CheckNicknameAPI.swift
- Projects/DonWorryNetworking/Sources/APIs/User/DeregisterAPI.swift
- Projects/DonWorryNetworking/Sources/APIs/User/LogoutAPI.swift
- Projects/DonWorryNetworking/Sources/DTO/LogoutDTO.swift
> ✨닉네임 중복 처리

- Projects/DesignSystem/Sources/TextField/LimitTextField.swift
- Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/Views/RecievedMoneyTableViewCell.swift
- 닉네임을 10자로 제한하기로했습니다(받을돈 view에서 닉네임이 너무길어지면 ui상으로 짤립니다)
- limittextfield에서 닉네임 글자제한 10개
- 받을돈디테일뷰에서 글자와 금액 width조절
> :adhesive_bandage: 닉네임글자수제한 및 받을돈ui수정

- Projects/DesignSystem/Sources/TextField/LimitTextField.swift
- Projects/DonWorry/Sources/UI/Auth/EnterUserInfo/EnterUserInfoViewController.swift
- Projects/DonWorry/Sources/UI/Profile/Cells/ProfileTableViewUserCell.swift
- Projects/DonWorry/Sources/UI/Profile/ProfileViewController.swift
- Projects/DonWorry/Sources/UI/Profile/ProfileViewReactor.swift
- Projects/DonWorry/Sources/UI/Profile/Views/ProfileTableView.swift
- Projects/DonWorry/Sources/UI/ProfileEditView/AccountEditViewController.swift
- Projects/DonWorry/Sources/UI/ProfileEditView/NicknameEditViewController.swift
- 계좌번호 숫자만 입력 받기
- 프로필 사진 수정 버튼 영역 확대
- 강제 언래핑 제거
> ♻️[QA] 프로필 관련 수정

- Projects/DonWorry/Sources/UI/Profile/Cells/ProfileTableViewAccountCell.swift
- Projects/DonWorry/Sources/UI/Profile/Cells/ProfileTableViewUserCell.swift
> ♻️프로필 수정 버튼 영역 확대

- Projects/Core/DonWorryExtensions/Sources/UIDevice+Utils.swift
- Projects/Core/DonWorryExtensions/Sources/UIWindow+Utils.swift
- Projects/DonWorry/Sources/Global/Toast/DWToastFactory.swift
- Projects/DonWorry/Sources/UI/ParticipatePaymentCard/ParticipatePaymentCardViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardDeco/PaymentCardDecoViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardIconEdit/PaymentCardIconEditViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardNameEdit/PaymentCardNameEditViewController.swift
- Projects/DonWorry/Sources/UI/Profile/ProfileViewController.swift
- Projects/DonWorry/Sources/UI/Profile/Views/AccountButtonStackView.swift
- Projects/DonWorry/Sources/UI/ProfileEditView/AcountEdit/AccountEditViewController.swift
- Projects/DonWorry/Sources/UI/ProfileEditView/NicknameEdit/NicknameEditViewController.swift
- Projects/DonWorry/Sources/UI/SpaceName/SpaceNameReactor.swift
- Projects/DonWorry/Sources/UI/SpaceName/SpaceNameViewController.swift
- Projects/DonWorry/SupportingFiles/DonWorry-Info.plist
- Projects/DonWorryNetworking/Sources/DTO/TestUserDTO.swift
- 관련 Issue : Closes #관련이슈
- 하단 버튼 위치 수정
- 카드데코 시 사진선택 언어 수정
- 카드리스트 오토레이아웃 수정
- 정산방 이름 설정 버튼 텍스트 수정
하기와 같이 버튼을 떼어주었습니다 (해당 에러가 발생하는 모든 뷰)
| 작업 전 | 작업 후 |
|   <img width ="200" src="https://user-images.githubusercontent.com/63157395/190919681-98294120-bd47-4022-96da-2e5eac16393f.png">   |    <img width ="200" src="https://user-images.githubusercontent.com/63157395/190919696-2ff45321-a584-4151-9ee0-3d4edcb0e7e4.png">   |
> ♻️ UI 버그 수정 (노치없는기기 및 SE대응)

- Projects/Core/DonWorryExtensions/Sources/UIView+Utils.swift
- Projects/DesignSystem/Sources/Button/DWBaseButton.swift
- Projects/DesignSystem/Sources/NavigationBar/DWNavigationBar.swift
- Projects/DonWorry/Sources/UI/Home/Cells/GiveBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/Cells/LeaveSpaceBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/Cells/StateBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/Cells/TakeBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/HomeViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardList/Cells/AddPaymentCardCollectionViewCell.swift
- 관련 Issue : Closes #관련이슈
- + 버튼 원래대로 고치기
- 카드 누를 때 애니메이션
- 네비게이션바 오른쪽아이템 버튼 눌리는 영역 수정
https://user-images.githubusercontent.com/63157395/191050286-8cc751cf-8035-4bce-ba65-52562ddd45f5.mp4
> 🔮 UI 버그 수정 및 홈 카드 애니메이션 추가

- Projects/DonWorry/Sources/UI/Home/Cells/GiveBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/Cells/LeaveSpaceBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/Cells/StateBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/Cells/TakeBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/HomeViewController.swift
- 관련 Issue : Closes #관련이슈
- 홈카드 애니메이션에 버그가 있어서 긴급 삭제합니다
| 작업 전 | 작업 후 |
|      |       |
> 🐞 홈 카드 애니메이션 제거

- Projects/DonWorry/Sources/Domain/Alarm/Model/AlarmModels.swift
- Projects/DonWorry/Sources/Domain/Alarm/Repository/AlarmRepository.swift
- Projects/DonWorry/Sources/Domain/Alarm/Service/AlarmService.swift
- Projects/DonWorry/Sources/Domain/Auth/UseCase/DeRegisterUseCase.swift
- Projects/DonWorry/Sources/UI/Home/Cells/StateBillCardCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/Home/HomePresenter.swift
- Projects/DonWorry/Sources/UI/Home/HomeReactor.swift
- Projects/DonWorry/Sources/UI/Home/HomeViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardList/Views/PaymentCardInRoomView.swift
- Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/ReceivedMoneyDetailReactor.swift
- Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/ReceivedMoneyDetailViewController.swift
- Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/Views/RecievedMoneyTableViewCell.swift
- Projects/DonWorryNetworking/Sources/APIs/Alarm/PushPaymentAPI.swift
- Projects/DonWorryNetworking/Sources/DonWorryNetwork/DonWorryProvider.swift
- Projects/DonWorryNetworking/Sources/DonWorryNetwork/DonWorrySession.swift
> 🐛 2차 QA 2차 반영

- Projects/DonWorry/Sources/UI/SentMoneyDetail/Views/SentMoneyTableViewCell.swift
- 서버에서 이미지이름이아니라 url로 보내주는 상태라 url에서 이미지 이름을 뽑아내서 구현했습니다
- 아이스크림이미지의 경우 세로가 긴형태라 아이스크림일때는 이미지 크기를 살짝 바꾸도록 분기처리 했습니다
- url에서 subscript로 이미지이름을 뽑아서 assetName으로 image를 넣어줬습니다
> :bug: 서버에서 이미지 못불러오는 버그 수정

- Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewReactor.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/Views/DetailImageViewController.swift
> feat: 디테일 사진 뷰

- Projects/DonWorry/Sources/UI/ParticipatePaymentCard/Views/ParticipateCardView.swift
- 카드 유저닉네임 길 경우 잘리는 것 막기
| 작업 전 | 작업 후 |
|  <img width="200" alt="앱아이콘" src="https://user-images.githubusercontent.com/77485339/191241403-d493404e-4981-45ac-82c4-ee24ebfa7e01.png">    |  <img width="200" alt="앱아이콘" src="https://user-images.githubusercontent.com/77485339/191241207-635352ca-5742-4fbd-9607-9f7fb71352ba.png">     |
> 카드 유저닉네임 길 경우 잘리는 것 수정

- Projects/DonWorry/Sources/UI/PaymentCardAmountEdit/PaymentCardAmountEditViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardAmountEdit/Views/NumberPadCollectionView.swift
- AmountEditView 오토레이아웃 전체 기기 대응
- 기기별로 달라서 깨지던 키보드를 통일했습니다
> 🔮AmountEditView 오토레이아웃 전체 기기 대응

- Projects/DonWorry/Sources/UI/Auth/AgreeTerm/AgreeTermViewController.swift
- Projects/DonWorry/Sources/UI/Auth/AgreeTerm/Cells/AgreeTermTableViewCell.swift
- Projects/DonWorry/Sources/UI/Auth/ConfirmTerm/ConfirmTermViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardAmountEdit/PaymentCardAmountEditReactor.swift
- 이용약관 버튼 확대
- 정산 금액 최대 10억
- 약관 확인 모달 수정
> 이용약관 버튼 및 약관 확인 모달 수정

- Projects/DesignSystem/Sources/TextField/LimitTextField.swift
- Projects/DonWorry/Sources/UI/Auth/EnterUserInfo/EnterUserInfoViewController.swift
- Projects/DonWorry/Sources/UI/Auth/EnterUserInfo/EnterUserInfoViewReactor.swift
- Projects/DonWorry/Sources/UI/SelectBank/Views/SelectBankCollectionView.swift
- 은행 선택 화면이 mini 또는 SE등의 디바이스에서 이상하게 나오는 이슈가 있었습니다.
- 닉네임, 계좌번호, 정산방 이름, 정산방 코드 등의 텍스트필드 입력을 알맞게 제한합니다.
| mini 기종 | SE 기종 |
| <img src="https://user-images.githubusercontent.com/88371913/192248727-8b5fc6fc-f646-4d31-b84b-66e231dd8954.png" width="300"> | <img src="https://user-images.githubusercontent.com/88371913/192248806-cd213394-75d5-412c-9a69-d86bcdf12baf.png" width="300"> |
> ♻️은행 선택 화면 및 TextField 유효성 검사

- Projects/DonWorry/Sources/App/AppDelegate.swift
- Projects/DonWorry/Sources/Domain/Auth/Repository/DeviceTokenRepository.swift
- Projects/DonWorry/Sources/Domain/Auth/UseCase/SignInUseCase.swift
- Projects/DonWorry/Sources/Domain/Auth/UseCase/SignUpUseCase.swift
- Projects/DonWorryLocalStorage/Sources/UserDefaultsKey.swift
- 관련 Issue : Closes #213
- `UIApplication.shared.registerForRemoteNotifications()` 를 메인쓰레드 작업으로 옮겼습니다 -> 오류나는애
- FCM 토큰을 디바이스 토큰이 들어가도록 했어요
요 토큰 
요기에쏙
> ✨ FCM 에서 Device Token으로 교체

- Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewReactor.swift
- 카드 디테일에서 참석 확인, 참석 취소 기능
<p>
</p>
> ✨카드 디테일에서 참석 확인, 참석 취소 기능 추가

- Projects/DonWorry/Sources/UI/ParticipatePaymentCard/Views/ParticipateCardView.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/PaymentCardDetailViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/Views/AttendanceCollectionViewCell.swift
- Projects/DonWorry/Sources/UI/PaymentCardDetail/Views/DetailImageViewController.swift
- 사진 디테일뷰 버튼크기 줄이기
- 정산 디테일뷰 - 유저 이름 왼쪽에 붙는 것
- 참석확인뷰 - 유저 이름 잘리는것 수정
| 작업 전 | 작업 후 |
|      |      <img width="200" src="https://user-images.githubusercontent.com/77485339/192757206-db2392f1-6e3b-4e1c-9796-dae37327399a.jpeg"> |
| 작업 전 | 작업 후 |
|      |      <img width="200" src="https://user-images.githubusercontent.com/77485339/192757576-cdaf40a6-47ba-47d2-b149-3a9aa6d93b70.jpeg"> |
| 작업 전 | 작업 후 |
|      |      <img width="200" src="https://user-images.githubusercontent.com/77485339/192757482-949e98df-48fe-4b0c-93ab-c7cfaba47546.jpeg"> |
> 사진디테일뷰 버튼크기 줄이기, 이름 왼쪽에 붙는 것 수정

- Projects/DonWorry/Sources/UI/Alarm/Cells/AlarmTableViewCell.swift
- Projects/DonWorry/Sources/UI/ReceivedMoneyDetail/Views/RecievedMoneyTableViewCell.swift
- Projects/DonWorry/Sources/UI/SentMoneyDetail/Views/SentMoneyTableViewCell.swift
- scaleToFit을 scaleToFill로 변경했습니다
> :lipstick: scaleToFit을 scaleToFill로 변경

- Projects/Core/DonWorryExtensions/Sources/UIScreen+Utils.swift
- Projects/DonWorry/Sources/UI/PaymentCardIconEdit/PaymentCardIconEditViewController.swift
- Projects/DonWorry/Sources/UI/PaymentCardIconEdit/PaymentCardIconEditViewReactor.swift
- Projects/DonWorry/Sources/UI/PaymentCardList/PaymentCardListViewController.swift
- Closes #236 
- Closes #237 
- 카테고리 아이콘추가에 따른 반응형 대응 (SE, Mini)
- 카드리스트 카드 없는 상태에서도 항상 scroll 가능하게 변경
https://user-images.githubusercontent.com/63157395/194806862-4065e64a-3cce-46d5-949b-67f15272cce6.MP4
> 카테고리 아이콘추가에 따른 반응형 대응 및 카드리스트 always-scrollable
